import { NextResponse } from "next/server";
import type { PortfolioApiResponse, Transaction, KpiData } from "@/lib/types";

/**
 * Mock portfolio API — returns realistic KPI + transaction data
 * modeled on the real Streamlit trading section schema.
 *
 * Replace this with a real backend call (e.g., FastAPI or direct DB query)
 * when you're ready to go live.
 */

const transactions: Transaction[] = [
  {
    id: 1,
    symbol: "MABANEE.KW",
    date: "2025-12-15",
    portfolio: "KFH",
    type: "Buy",
    category: "TRADE",
    status: "Unrealized",
    source: "MANUAL",
    quantity: 5000,
    price: 0.82,
    avgCost: 0.82,
    currentPrice: 0.905,
    sellPrice: 0,
    value: 4100,
    pnl: 425,
    pnlPct: 10.37,
    fees: 4.1,
    dividend: 0,
    bonusShares: 0,
    notes: "Initial position",
  },
  {
    id: 2,
    symbol: "NBK.KW",
    date: "2025-11-20",
    portfolio: "KFH",
    type: "Buy",
    category: "TRADE",
    status: "Unrealized",
    source: "UPLOAD",
    quantity: 2000,
    price: 1.12,
    avgCost: 1.12,
    currentPrice: 1.18,
    sellPrice: 0,
    value: 2240,
    pnl: 120,
    pnlPct: 5.36,
    fees: 2.24,
    dividend: 0,
    bonusShares: 0,
    notes: "",
  },
  {
    id: 3,
    symbol: "ZAIN.KW",
    date: "2025-11-10",
    portfolio: "BBYN",
    type: "Buy",
    category: "TRADE",
    status: "Unrealized",
    source: "MANUAL",
    quantity: 10000,
    price: 0.64,
    avgCost: 0.64,
    currentPrice: 0.685,
    sellPrice: 0,
    value: 6400,
    pnl: 450,
    pnlPct: 7.03,
    fees: 6.4,
    dividend: 0,
    bonusShares: 0,
    notes: "Long-term hold",
  },
  {
    id: 4,
    symbol: "KRE",
    date: "2025-10-05",
    portfolio: "USA",
    type: "Buy",
    category: "TRADE",
    status: "Unrealized",
    source: "API",
    quantity: 50,
    price: 52.3,
    avgCost: 52.3,
    currentPrice: 55.9,
    sellPrice: 0,
    value: 2615,
    pnl: 180,
    pnlPct: 6.88,
    fees: 1.0,
    dividend: 0,
    bonusShares: 0,
    notes: "US banking sector",
  },
  {
    id: 5,
    symbol: "AGILITY.KW",
    date: "2025-09-20",
    portfolio: "KFH",
    type: "Sell",
    category: "TRADE",
    status: "Realized",
    source: "MANUAL",
    quantity: 3000,
    price: 0.96,
    avgCost: 0.88,
    currentPrice: 0,
    sellPrice: 0.96,
    value: 2880,
    pnl: 240,
    pnlPct: 9.09,
    fees: 2.88,
    dividend: 0,
    bonusShares: 0,
    notes: "Profit taking",
  },
  {
    id: 6,
    symbol: "HUMANSOFT.KW",
    date: "2025-09-01",
    portfolio: "KFH",
    type: "Buy",
    category: "TRADE",
    status: "Unrealized",
    source: "MANUAL",
    quantity: 1500,
    price: 3.24,
    avgCost: 3.24,
    currentPrice: 3.15,
    sellPrice: 0,
    value: 4860,
    pnl: -135,
    pnlPct: -2.78,
    fees: 4.86,
    dividend: 0,
    bonusShares: 0,
    notes: "Education sector",
  },
  {
    id: 7,
    symbol: "ZAIN.KW",
    date: "2025-08-15",
    portfolio: "BBYN",
    type: "Dividend",
    category: "INCOME",
    status: "Income",
    source: "MANUAL",
    quantity: 10000,
    price: 0,
    avgCost: 0.64,
    currentPrice: 0.685,
    sellPrice: 0,
    value: 250,
    pnl: 250,
    pnlPct: 0,
    fees: 0,
    dividend: 250,
    bonusShares: 0,
    notes: "Annual dividend",
  },
  {
    id: 8,
    symbol: "BOUBYAN.KW",
    date: "2025-08-01",
    portfolio: "BBYN",
    type: "Buy",
    category: "TRADE",
    status: "Unrealized",
    source: "UPLOAD",
    quantity: 4000,
    price: 0.72,
    avgCost: 0.72,
    currentPrice: 0.78,
    sellPrice: 0,
    value: 2880,
    pnl: 240,
    pnlPct: 8.33,
    fees: 2.88,
    dividend: 0,
    bonusShares: 0,
    notes: "",
  },
  {
    id: 9,
    symbol: "AAPL",
    date: "2025-07-10",
    portfolio: "USA",
    type: "Buy",
    category: "TRADE",
    status: "Unrealized",
    source: "API",
    quantity: 20,
    price: 198.5,
    avgCost: 198.5,
    currentPrice: 227.63,
    sellPrice: 0,
    value: 3970,
    pnl: 582.6,
    pnlPct: 14.68,
    fees: 0.5,
    dividend: 0,
    bonusShares: 0,
    notes: "Core tech holding",
  },
  {
    id: 10,
    symbol: "MABANEE.KW",
    date: "2025-07-01",
    portfolio: "KFH",
    type: "Bonus Shares",
    category: "CORPORATE_ACTION",
    status: "Bonus",
    source: "MANUAL",
    quantity: 500,
    price: 0,
    avgCost: 0.745,
    currentPrice: 0.905,
    sellPrice: 0,
    value: 0,
    pnl: 0,
    pnlPct: 0,
    fees: 0,
    dividend: 0,
    bonusShares: 500,
    notes: "10% bonus issue",
  },
  {
    id: 11,
    symbol: "",
    date: "2025-06-15",
    portfolio: "KFH",
    type: "Deposit",
    category: "FLOW_IN",
    status: "",
    source: "MANUAL",
    quantity: 0,
    price: 0,
    avgCost: 0,
    currentPrice: 0,
    sellPrice: 0,
    value: 5000,
    pnl: 0,
    pnlPct: 0,
    fees: 0,
    dividend: 0,
    bonusShares: 0,
    notes: "Initial funding",
  },
  {
    id: 12,
    symbol: "",
    date: "2025-06-15",
    portfolio: "BBYN",
    type: "Deposit",
    category: "FLOW_IN",
    status: "",
    source: "MANUAL",
    quantity: 0,
    price: 0,
    avgCost: 0,
    currentPrice: 0,
    sellPrice: 0,
    value: 10000,
    pnl: 0,
    pnlPct: 0,
    fees: 0,
    dividend: 0,
    bonusShares: 0,
    notes: "Initial funding",
  },
  {
    id: 13,
    symbol: "STC.KW",
    date: "2026-01-08",
    portfolio: "KFH",
    type: "Buy",
    category: "TRADE",
    status: "Unrealized",
    source: "MANUAL",
    quantity: 8000,
    price: 0.915,
    avgCost: 0.915,
    currentPrice: 0.94,
    sellPrice: 0,
    value: 7320,
    pnl: 200,
    pnlPct: 2.73,
    fees: 7.32,
    dividend: 0,
    bonusShares: 0,
    notes: "Telecom play",
  },
  {
    id: 14,
    symbol: "GBK.KW",
    date: "2026-01-15",
    portfolio: "BBYN",
    type: "Sell",
    category: "TRADE",
    status: "Realized",
    source: "MANUAL",
    quantity: 6000,
    price: 0.345,
    avgCost: 0.31,
    currentPrice: 0,
    sellPrice: 0.345,
    value: 2070,
    pnl: 210,
    pnlPct: 11.29,
    fees: 2.07,
    dividend: 0,
    bonusShares: 0,
    notes: "Full exit",
  },
  {
    id: 15,
    symbol: "MSFT",
    date: "2026-02-01",
    portfolio: "USA",
    type: "Dividend",
    category: "INCOME",
    status: "Income",
    source: "API",
    quantity: 15,
    price: 0,
    avgCost: 380.0,
    currentPrice: 415.2,
    sellPrice: 0,
    value: 11.25,
    pnl: 11.25,
    pnlPct: 0,
    fees: 0,
    dividend: 11.25,
    bonusShares: 0,
    notes: "Quarterly dividend",
  },
];

const kpis: KpiData = {
  totalBuys: 34385,
  totalSells: 4950,
  totalDeposits: 15000,
  totalWithdrawals: 0,
  unrealizedPnl: 2062.6,
  realizedPnl: 450,
  totalPnl: 2512.6,
  totalTransactions: transactions.length,
  cashDividends: 511.25,
  totalFees: 34.25,
  netCashFlow: -14473.75,
  totalReturnPct: 8.79,
  buyCount: 7,
  sellCount: 2,
  depositCount: 2,
  withdrawalCount: 0,
  dividendCount: 2,
};

export async function GET() {
  // Simulate slight network delay
  await new Promise((r) => setTimeout(r, 200));

  const response: PortfolioApiResponse = { kpis, transactions };
  return NextResponse.json(response);
}
